name: sync-fork

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00
  workflow_dispatch: # or manually from UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GH_PAT }}
          owner: lerna
          base: main
          head: main
          merge_method: rebase
